export type ScraperType = 'fetch' | 'puppeteer';

export interface StoreConfig {
  id: string;
  name: string;
  baseUrl: string;
  productListUrl: string;  // URL to paginated product listing
  scraperType: ScraperType;
  isOnline: boolean;
  isPhysical: boolean;
  mallLocation: string | null;
  mapsUrl: string | null;
  // CSS selectors for fetch scraper (not needed for puppeteer stores)
  selectors?: {
    productContainer: string;  // selector for each product card
    name: string;              // product name within card
    price: string;             // price within card
    image: string;             // img tag within card
    link: string;              // anchor tag within card
    nextPage?: string;         // pagination next button
  };
}

export const STORES: StoreConfig[] = [
  // ─── PUPPETEER (Inditex platform + COS) ───────────────────────────────
  {
    id: 'zara',
    name: 'Zara Qatar',
    baseUrl: 'https://www.zara.com',
    productListUrl: 'https://www.zara.com/qa/en/woman-new-in-l1180.html',
    scraperType: 'puppeteer',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Doha Festival City',
    mapsUrl: 'https://maps.google.com/?q=Zara+Doha+Festival+City',
  },
  {
    id: 'massimodutti',
    name: 'Massimo Dutti Qatar',
    baseUrl: 'https://www.massimodutti.com',
    productListUrl: 'https://www.massimodutti.com/qa/en/woman-l536.html',
    scraperType: 'puppeteer',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Villaggio Mall',
    mapsUrl: 'https://maps.google.com/?q=Massimo+Dutti+Villaggio+Mall+Doha',
  },
  {
    id: 'pullandbear',
    name: 'Pull&Bear Qatar',
    baseUrl: 'https://www.pullandbear.com',
    productListUrl: 'https://www.pullandbear.com/qa/woman-l11097.html',
    scraperType: 'puppeteer',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Mall of Qatar',
    mapsUrl: 'https://maps.google.com/?q=Pull+Bear+Mall+of+Qatar',
  },
  {
    id: 'bershka',
    name: 'Bershka Qatar',
    baseUrl: 'https://www.bershka.com',
    productListUrl: 'https://www.bershka.com/qa/women/clothes/sales-n5303.html',
    scraperType: 'puppeteer',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Mall of Qatar',
    mapsUrl: 'https://maps.google.com/?q=Bershka+Mall+of+Qatar',
  },
  {
    id: 'stradivarius',
    name: 'Stradivarius Qatar',
    baseUrl: 'https://www.stradivarius.com',
    productListUrl: 'https://www.stradivarius.com/qa/woman-l11097.html',
    scraperType: 'puppeteer',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Doha Festival City',
    mapsUrl: 'https://maps.google.com/?q=Stradivarius+Doha+Festival+City',
  },
  {
    id: 'lefties',
    name: 'Lefties Qatar',
    baseUrl: 'https://www.lefties.com',
    productListUrl: 'https://www.lefties.com/qa/woman-l11097.html',
    scraperType: 'puppeteer',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Doha',
    mapsUrl: 'https://maps.google.com/?q=Lefties+Doha',
  },
  {
    id: 'cos',
    name: 'COS Qatar',
    baseUrl: 'https://www.cosstores.com',
    productListUrl: 'https://www.cosstores.com/en_gb/women/all/',
    scraperType: 'puppeteer',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
  },

  // ─── FETCH + CHEERIO ──────────────────────────────────────────────────
  {
    id: 'hm',
    name: 'H&M Qatar',
    baseUrl: 'https://www2.hm.com',
    productListUrl: 'https://www2.hm.com/en_qa/women/new-arrivals/clothes.html',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Doha Festival City',
    mapsUrl: 'https://maps.google.com/?q=HM+Doha+Festival+City',
    selectors: {
      productContainer: 'li.product-item',
      name: 'h2.item-heading',
      price: 'span.price',
      image: 'img.item-image',
      link: 'a.item-link',
    },
  },
  {
    id: 'mango',
    name: 'Mango Qatar',
    baseUrl: 'https://shop.mango.com',
    productListUrl: 'https://shop.mango.com/qa/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Mall of Qatar',
    mapsUrl: 'https://maps.google.com/?q=Mango+Mall+of+Qatar',
    selectors: {
      productContainer: 'article.product',
      name: 'h2.product-name',
      price: 'span.price',
      image: 'img.product-image',
      link: 'a.product-link',
    },
  },
  {
    id: 'mandS',
    name: 'Marks & Spencer Qatar',
    baseUrl: 'https://www.marksandspencerme.com',
    productListUrl: 'https://www.marksandspencerme.com/en-qa/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Doha Festival City',
    mapsUrl: 'https://maps.google.com/?q=Marks+Spencer+Doha+Festival+City',
    selectors: {
      productContainer: 'div.product-tile',
      name: 'span.product-name',
      price: 'span.price',
      image: 'img',
      link: 'a.product-tile-link',
    },
  },
  {
    id: 'namshi',
    name: 'Namshi',
    baseUrl: 'https://www.namshi.com',
    productListUrl: 'https://www.namshi.com/qatar-en/women-clothing/',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div.product-card',
      name: 'p.product-name',
      price: 'span.price',
      image: 'img.product-image',
      link: 'a',
    },
  },
  {
    id: 'noon',
    name: 'Noon Fashion',
    baseUrl: 'https://www.noon.com',
    productListUrl: 'https://www.noon.com/qatar-en/fashion-women/',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div[class*="productContainer"]',
      name: 'div[class*="name"]',
      price: 'strong[class*="amount"]',
      image: 'img',
      link: 'a',
    },
  },
  {
    id: '6thstreet',
    name: '6th Street',
    baseUrl: 'https://en-qa.6thstreet.com',
    productListUrl: 'https://en-qa.6thstreet.com/women.html',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div.product-item-info',
      name: 'strong.product-item-name',
      price: 'span.price',
      image: 'img.product-image-photo',
      link: 'a.product-item-link',
    },
  },
  {
    id: 'asos',
    name: 'ASOS',
    baseUrl: 'https://www.asos.com',
    productListUrl: 'https://www.asos.com/women/new-in/cat/?cid=27108',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'article[data-auto-id="productTile"]',
      name: 'p[data-auto-id="productTileDescription"]',
      price: 'span[data-auto-id="productTilePrice"]',
      image: 'img',
      link: 'a[data-auto-id="productTileLink"]',
    },
  },
  {
    id: 'shein',
    name: 'Shein Qatar',
    baseUrl: 'https://www.shein.com',
    productListUrl: 'https://www.shein.com/Women-Dresses-c-1727.html',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'li.S-product-item',
      name: 'a.goods-title-link',
      price: 'span.normal-price-ctn__sale-price',
      image: 'img.crop-image-container__img',
      link: 'a.S-product-item__img-container',
    },
  },
  {
    id: 'centrepoint',
    name: 'Centrepoint Qatar',
    baseUrl: 'https://www.centrepoint.com',
    productListUrl: 'https://www.centrepoint.com/qa/en/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Doha',
    mapsUrl: 'https://maps.google.com/?q=Centrepoint+Doha',
    selectors: {
      productContainer: 'div.product-item',
      name: 'div.product-name',
      price: 'span.price',
      image: 'img',
      link: 'a',
    },
  },
  {
    id: 'charleskeith',
    name: 'Charles & Keith',
    baseUrl: 'https://www.charleskeith.com',
    productListUrl: 'https://www.charleskeith.com/qa/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div.product-tile',
      name: 'div.product-tile__name',
      price: 'span.price-sales',
      image: 'img.tile-image',
      link: 'a.product-tile__link',
    },
  },
  {
    id: 'aldo',
    name: 'Aldo Qatar',
    baseUrl: 'https://www.aldoshoes.com',
    productListUrl: 'https://www.aldoshoes.com/qa/en/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div.product-tile',
      name: 'span.product-tile__title',
      price: 'span.price',
      image: 'img.product-tile__image',
      link: 'a.product-tile__link',
    },
  },
  {
    id: 'maxfashion',
    name: 'Max Fashion Qatar',
    baseUrl: 'https://www.maxfashion.com',
    productListUrl: 'https://www.maxfashion.com/qa/en/department/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'City Center Doha',
    mapsUrl: 'https://maps.google.com/?q=Max+Fashion+City+Center+Doha',
    selectors: {
      productContainer: 'div.product-item',
      name: 'div.product-name',
      price: 'span.price',
      image: 'img',
      link: 'a',
    },
  },
  {
    id: 'splash',
    name: 'Splash Qatar',
    baseUrl: 'https://www.splashfashions.com',
    productListUrl: 'https://www.splashfashions.com/qa/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'City Center Doha',
    mapsUrl: 'https://maps.google.com/?q=Splash+City+Center+Doha',
    selectors: {
      productContainer: 'div.product-item',
      name: 'div.product-name',
      price: 'span.price',
      image: 'img',
      link: 'a',
    },
  },
  {
    id: 'lcwaikiki',
    name: 'LC Waikiki Qatar',
    baseUrl: 'https://www.lcwaikiki.com',
    productListUrl: 'https://www.lcwaikiki.com/en-QA/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: true,
    mallLocation: 'Mall of Qatar',
    mapsUrl: 'https://maps.google.com/?q=LC+Waikiki+Mall+of+Qatar',
    selectors: {
      productContainer: 'div.product-item',
      name: 'span.product-name',
      price: 'span.price',
      image: 'img',
      link: 'a',
    },
  },
  {
    id: 'vogacloset',
    name: 'VogaCloset',
    baseUrl: 'https://vogacloset.com',
    productListUrl: 'https://vogacloset.com/qatar/en/women/clothing',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div.product-item',
      name: 'div.product-name',
      price: 'span.price',
      image: 'img',
      link: 'a',
    },
  },
  {
    id: 'americaneagle',
    name: 'American Eagle',
    baseUrl: 'https://www.ae.com',
    productListUrl: 'https://www.ae.com/us/en/c/women/category/cat6300001',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div.product-tile',
      name: 'span.product-tile__name',
      price: 'span.product-tile__unit-price',
      image: 'img.product-tile__image',
      link: 'a.product-tile__link',
    },
  },
  {
    id: 'newyorker',
    name: 'New Yorker Qatar',
    baseUrl: 'https://www.newyorker.de',
    productListUrl: 'https://www.newyorker.de/en/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div.product-tile',
      name: 'span.product-name',
      price: 'span.price',
      image: 'img',
      link: 'a',
    },
  },
  {
    id: 'riva',
    name: 'Riva Fashion',
    baseUrl: 'https://www.rivafashion.com',
    productListUrl: 'https://www.rivafashion.com/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div.product-item',
      name: 'div.product-name',
      price: 'span.price',
      image: 'img',
      link: 'a',
    },
  },
  {
    id: 'koton',
    name: 'Koton Qatar',
    baseUrl: 'https://www.koton.com',
    productListUrl: 'https://www.koton.com/qa/women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div.product-item',
      name: 'div.product-name',
      price: 'span.price',
      image: 'img',
      link: 'a',
    },
  },
  {
    id: 'next',
    name: 'Next Qatar',
    baseUrl: 'https://www.next.com',
    productListUrl: 'https://www.next.com/qa/shop/gender-women',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div[data-testid="product"]',
      name: 'p[data-testid="product-description"]',
      price: 'span[data-testid="product-price"]',
      image: 'img',
      link: 'a',
    },
  },
  {
    id: 'urbanoutfitters',
    name: 'Urban Outfitters',
    baseUrl: 'https://www.urbanoutfitters.com',
    productListUrl: 'https://www.urbanoutfitters.com/womens-new-arrivals',
    scraperType: 'fetch',
    isOnline: true,
    isPhysical: false,
    mallLocation: null,
    mapsUrl: null,
    selectors: {
      productContainer: 'div[class*="c-pwa-tile-grid-item"]',
      name: 'div[class*="c-pwa-product-tile__description"]',
      price: 'div[class*="c-pwa-product-tile__price"]',
      image: 'img',
      link: 'a',
    },
  },
];
