export const stores = [
  { id: 'namshi', name: 'Namshi', logoUrl: 'https://www.namshi.com/favicon.ico', website: 'https://www.namshi.com/qatar-en/', mallLocation: null, mapsUrl: null, isOnline: true, isPhysical: false },
  { id: 'noon', name: 'Noon Fashion', logoUrl: 'https://www.noon.com/favicon.ico', website: 'https://www.noon.com/qatar-en/fashion-women/', mallLocation: null, mapsUrl: null, isOnline: true, isPhysical: false },
  { id: 'ounass', name: 'Ounass', logoUrl: 'https://www.ounass.com/favicon.ico', website: 'https://www.ounass.com', mallLocation: null, mapsUrl: null, isOnline: true, isPhysical: false },
  { id: '6thstreet', name: '6th Street', logoUrl: 'https://en-qa.6thstreet.com/favicon.ico', website: 'https://en-qa.6thstreet.com', mallLocation: null, mapsUrl: null, isOnline: true, isPhysical: false },
  { id: 'vogacloset', name: 'VogaCloset', logoUrl: 'https://vogacloset.com/favicon.ico', website: 'https://vogacloset.com/qatar/', mallLocation: null, mapsUrl: null, isOnline: true, isPhysical: false },
  { id: 'bfab', name: 'bfab', logoUrl: 'https://bfab.com/favicon.ico', website: 'https://bfab.com/qa_en', mallLocation: null, mapsUrl: null, isOnline: true, isPhysical: false },
  { id: 'zara', name: 'Zara Qatar', logoUrl: 'https://www.zara.com/favicon.ico', website: 'https://www.zara.com/qa/', mallLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=Zara+Doha+Festival+City', isOnline: true, isPhysical: true },
  { id: 'massimodutti', name: 'Massimo Dutti Qatar', logoUrl: 'https://www.massimodutti.com/favicon.ico', website: 'https://www.massimodutti.com/qa/', mallLocation: 'Villaggio Mall', mapsUrl: 'https://maps.google.com/?q=Massimo+Dutti+Villaggio+Mall+Doha', isOnline: true, isPhysical: true },
  { id: 'hm', name: 'H&M Qatar', logoUrl: 'https://www2.hm.com/favicon.ico', website: 'https://www2.hm.com/en_qa/', mallLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=HM+Doha+Festival+City', isOnline: true, isPhysical: true },
  { id: 'mango', name: 'Mango Qatar', logoUrl: 'https://shop.mango.com/favicon.ico', website: 'https://shop.mango.com/qa', mallLocation: 'Mall of Qatar', mapsUrl: 'https://maps.google.com/?q=Mango+Mall+of+Qatar', isOnline: true, isPhysical: true },
  { id: 'mandS', name: 'Marks & Spencer Qatar', logoUrl: 'https://www.marksandspencerme.com/favicon.ico', website: 'https://www.marksandspencerme.com/en-qa', mallLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=Marks+Spencer+Doha+Festival+City', isOnline: true, isPhysical: true },
  { id: 'pullandbear', name: 'Pull&Bear Qatar', logoUrl: 'https://www.pullandbear.com/favicon.ico', website: 'https://www.pullandbear.com/qa/', mallLocation: 'Mall of Qatar', mapsUrl: 'https://maps.google.com/?q=Pull+Bear+Mall+of+Qatar', isOnline: true, isPhysical: true },
  { id: 'bershka', name: 'Bershka Qatar', logoUrl: 'https://www.bershka.com/favicon.ico', website: 'https://www.bershka.com/qa/', mallLocation: 'Mall of Qatar', mapsUrl: 'https://maps.google.com/?q=Bershka+Mall+of+Qatar', isOnline: true, isPhysical: true },
  { id: 'stradivarius', name: 'Stradivarius Qatar', logoUrl: 'https://www.stradivarius.com/favicon.ico', website: 'https://www.stradivarius.com/qa/', mallLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=Stradivarius+Doha+Festival+City', isOnline: true, isPhysical: true },
  { id: 'galerieslafayette', name: 'Galeries Lafayette Doha', logoUrl: 'https://www.galerieslafayette.qa/favicon.ico', website: 'https://www.galerieslafayette.qa', mallLocation: 'Katara Cultural Village', mapsUrl: 'https://maps.google.com/?q=Galeries+Lafayette+Doha', isOnline: true, isPhysical: true },
  { id: 'maxfashion', name: 'Max Fashion Qatar', logoUrl: 'https://www.maxfashion.com/favicon.ico', website: 'https://www.maxfashion.com/qa/', mallLocation: 'City Center Doha', mapsUrl: 'https://maps.google.com/?q=Max+Fashion+City+Center+Doha', isOnline: true, isPhysical: true },
  { id: 'splash', name: 'Splash Qatar', logoUrl: 'https://www.splashfashions.com/favicon.ico', website: 'https://www.splashfashions.com/qa/', mallLocation: 'City Center Doha', mapsUrl: 'https://maps.google.com/?q=Splash+City+Center+Doha', isOnline: true, isPhysical: true },
  { id: 'lcwaikiki', name: 'LC Waikiki Qatar', logoUrl: 'https://www.lcwaikiki.com/favicon.ico', website: 'https://www.lcwaikiki.com/en-QA/', mallLocation: 'Mall of Qatar', mapsUrl: 'https://maps.google.com/?q=LC+Waikiki+Mall+of+Qatar', isOnline: true, isPhysical: true },
  { id: 'wadha', name: 'Wadha', logoUrl: '', website: 'https://www.instagram.com/wadha.official/', mallLocation: 'Doha', mapsUrl: 'https://maps.google.com/?q=Wadha+Doha', isOnline: false, isPhysical: true },
  { id: 'elisabietta', name: 'Elisabietta', logoUrl: '', website: 'https://www.instagram.com/elisabietta/', mallLocation: 'Doha', mapsUrl: 'https://maps.google.com/?q=Elisabietta+Doha', isOnline: false, isPhysical: true },
];

export const products = [
  // Zara Qatar
  { store: 'zara', name: 'Linen Blend Midi Dress', price: 299, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&q=80', productUrl: 'https://www.zara.com/qa/en/woman-dresses-l1066.html', category: 'dress', color: ['beige', 'white'], fabric: 'linen', style: ['flowy', 'casual'], fit: 'loose', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=Zara+Doha+Festival+City' },
  { store: 'zara', name: 'Floral Print Wrap Dress', price: 349, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&q=80', productUrl: 'https://www.zara.com/qa/en/woman-dresses-l1066.html', category: 'dress', color: ['floral', 'pink'], fabric: 'chiffon', style: ['elegant', 'flowy'], fit: 'fitted', occasion: ['casual', 'evening'], isOnline: true, inStoreLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=Zara+Doha+Festival+City' },
  { store: 'zara', name: 'Oversized Cotton Shirt', price: 189, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80', productUrl: 'https://www.zara.com/qa/en/woman-shirts-l1217.html', category: 'shirt', color: ['white'], fabric: 'cotton', style: ['casual', 'loose'], fit: 'oversized', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=Zara+Doha+Festival+City' },

  // H&M Qatar
  { store: 'hm', name: 'Long Linen Blend Skirt', price: 149, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=400&q=80', productUrl: 'https://www2.hm.com/en_qa/women/skirts.html', category: 'skirt', color: ['beige', 'sand'], fabric: 'linen', style: ['modest', 'casual'], fit: 'loose', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=HM+Doha+Festival+City' },
  { store: 'hm', name: 'Relaxed Fit Cotton Trousers', price: 129, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4be4?w=400&q=80', productUrl: 'https://www2.hm.com/en_qa/women/trousers.html', category: 'pants', color: ['black', 'navy'], fabric: 'cotton', style: ['casual', 'loose'], fit: 'loose', occasion: ['casual', 'work'], isOnline: true, inStoreLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=HM+Doha+Festival+City' },
  { store: 'hm', name: 'Chiffon Midi Dress', price: 199, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?w=400&q=80', productUrl: 'https://www2.hm.com/en_qa/women/dresses.html', category: 'dress', color: ['dusty pink'], fabric: 'chiffon', style: ['elegant', 'flowy'], fit: 'loose', occasion: ['evening', 'casual'], isOnline: true, inStoreLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=HM+Doha+Festival+City' },

  // Mango Qatar
  { store: 'mango', name: 'Satin Effect Midi Dress', price: 399, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=400&q=80', productUrl: 'https://shop.mango.com/qa/women/dresses', category: 'dress', color: ['black'], fabric: 'silk', style: ['elegant', 'fitted'], fit: 'fitted', occasion: ['evening', 'formal'], isOnline: true, inStoreLocation: 'Mall of Qatar', mapsUrl: 'https://maps.google.com/?q=Mango+Mall+of+Qatar' },
  { store: 'mango', name: 'Linen Wide-Leg Trousers', price: 279, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&q=80', productUrl: 'https://shop.mango.com/qa/women/trousers', category: 'pants', color: ['beige', 'ecru'], fabric: 'linen', style: ['casual', 'loose'], fit: 'loose', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: 'Mall of Qatar', mapsUrl: 'https://maps.google.com/?q=Mango+Mall+of+Qatar' },

  // Namshi
  { store: 'namshi', name: 'Modest Maxi Abaya Dress', price: 249, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=400&q=80', productUrl: 'https://www.namshi.com/qatar-en/women-clothing-dresses/', category: 'abaya', color: ['black'], fabric: 'polyester', style: ['modest', 'elegant'], fit: 'loose', occasion: ['everyday', 'formal'], isOnline: true, inStoreLocation: null, mapsUrl: null },
  { store: 'namshi', name: 'Floral Chiffon Blouse', price: 99, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=400&q=80', productUrl: 'https://www.namshi.com/qatar-en/women-clothing/', category: 'blouse', color: ['floral', 'blue'], fabric: 'chiffon', style: ['casual', 'flowy'], fit: 'loose', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: null, mapsUrl: null },
  { store: 'namshi', name: 'Denim Straight Jeans', price: 179, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&q=80', productUrl: 'https://www.namshi.com/qatar-en/women-clothing/', category: 'jeans', color: ['blue', 'dark blue'], fabric: 'denim', style: ['casual'], fit: 'slim', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: null, mapsUrl: null },

  // Noon
  { store: 'noon', name: 'Tommy Hilfiger Polo Dress', price: 499, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1550639525-c97d455acf70?w=400&q=80', productUrl: 'https://www.noon.com/qatar-en/fashion-women/', category: 'dress', color: ['navy', 'white'], fabric: 'cotton', style: ['casual', 'sporty'], fit: 'fitted', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: null, mapsUrl: null },
  { store: 'noon', name: 'Calvin Klein Slim Trousers', price: 389, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400&q=80', productUrl: 'https://www.noon.com/qatar-en/fashion-women/', category: 'pants', color: ['black'], fabric: 'polyester', style: ['formal', 'fitted'], fit: 'slim', occasion: ['work', 'formal'], isOnline: true, inStoreLocation: null, mapsUrl: null },

  // Massimo Dutti
  { store: 'massimodutti', name: 'Wool Blend Blazer', price: 799, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80', productUrl: 'https://www.massimodutti.com/qa/en/woman-coats-blazers-l540.html', category: 'jacket', color: ['camel', 'beige'], fabric: 'wool', style: ['elegant', 'formal'], fit: 'fitted', occasion: ['work', 'formal'], isOnline: true, inStoreLocation: 'Villaggio Mall', mapsUrl: 'https://maps.google.com/?q=Massimo+Dutti+Villaggio+Mall+Doha' },
  { store: 'massimodutti', name: 'Silk Blend Midi Skirt', price: 549, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1577900232427-18219b9166a0?w=400&q=80', productUrl: 'https://www.massimodutti.com/qa/en/woman-skirts-l1228.html', category: 'skirt', color: ['ivory', 'white'], fabric: 'silk', style: ['elegant', 'flowy'], fit: 'loose', occasion: ['evening', 'formal'], isOnline: true, inStoreLocation: 'Villaggio Mall', mapsUrl: 'https://maps.google.com/?q=Massimo+Dutti+Villaggio+Mall+Doha' },

  // Marks & Spencer
  { store: 'mandS', name: 'Pure Cotton Midi Shirt Dress', price: 229, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268217?w=400&q=80', productUrl: 'https://www.marksandspencerme.com/en-qa/women/dresses', category: 'dress', color: ['white', 'blue stripe'], fabric: 'cotton', style: ['casual', 'modest'], fit: 'loose', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=Marks+Spencer+Doha+Festival+City' },
  { store: 'mandS', name: 'Linen Blend Wide Leg Trousers', price: 199, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80', productUrl: 'https://www.marksandspencerme.com/en-qa/women/trousers', category: 'pants', color: ['navy', 'white'], fabric: 'linen', style: ['casual', 'loose'], fit: 'loose', occasion: ['casual', 'work'], isOnline: true, inStoreLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=Marks+Spencer+Doha+Festival+City' },

  // Bershka
  { store: 'bershka', name: 'Satin Mini Skirt', price: 129, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1571513722275-4b41940f54b8?w=400&q=80', productUrl: 'https://www.bershka.com/qa/woman/skirts', category: 'skirt', color: ['black', 'silver'], fabric: 'polyester', style: ['casual', 'fitted'], fit: 'fitted', occasion: ['evening', 'casual'], isOnline: true, inStoreLocation: 'Mall of Qatar', mapsUrl: 'https://maps.google.com/?q=Bershka+Mall+of+Qatar' },
  { store: 'bershka', name: 'Oversized Printed T-Shirt', price: 79, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80', productUrl: 'https://www.bershka.com/qa/woman/tops', category: 'top', color: ['white', 'grey'], fabric: 'cotton', style: ['casual', 'loose'], fit: 'oversized', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: 'Mall of Qatar', mapsUrl: 'https://maps.google.com/?q=Bershka+Mall+of+Qatar' },

  // Stradivarius
  { store: 'stradivarius', name: 'Flowy Maxi Dress', price: 219, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=400&q=80', productUrl: 'https://www.stradivarius.com/qa/woman/dresses', category: 'dress', color: ['olive', 'green'], fabric: 'polyester', style: ['flowy', 'casual', 'modest'], fit: 'loose', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: 'Doha Festival City', mapsUrl: 'https://maps.google.com/?q=Stradivarius+Doha+Festival+City' },

  // Pull&Bear
  { store: 'pullandbear', name: 'Denim Mom Jeans', price: 159, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=400&q=80', productUrl: 'https://www.pullandbear.com/qa/woman/jeans', category: 'jeans', color: ['light blue', 'blue'], fabric: 'denim', style: ['casual', 'loose'], fit: 'loose', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: 'Mall of Qatar', mapsUrl: 'https://maps.google.com/?q=Pull+Bear+Mall+of+Qatar' },

  // Ounass
  { store: 'ounass', name: 'Zimmermann Linen Midi Dress', price: 1899, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400&q=80', productUrl: 'https://www.ounass.com/women/clothing/dresses', category: 'dress', color: ['white', 'ivory'], fabric: 'linen', style: ['elegant', 'flowy', 'modest'], fit: 'loose', occasion: ['casual', 'evening'], isOnline: true, inStoreLocation: null, mapsUrl: null },
  { store: 'ounass', name: 'Self-Portrait Lace Top', price: 1299, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=400&q=80', productUrl: 'https://www.ounass.com/women/clothing/tops', category: 'top', color: ['white'], fabric: 'cotton', style: ['elegant', 'fitted'], fit: 'fitted', occasion: ['evening', 'formal'], isOnline: true, inStoreLocation: null, mapsUrl: null },

  // 6th Street
  { store: '6thstreet', name: 'Floral Wrap Midi Dress', price: 289, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&q=80', productUrl: 'https://en-qa.6thstreet.com/women/clothing/dresses', category: 'dress', color: ['floral', 'pink', 'blue'], fabric: 'chiffon', style: ['flowy', 'casual'], fit: 'loose', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: null, mapsUrl: null },

  // VogaCloset
  { store: 'vogacloset', name: 'Boohoo Satin Slip Dress', price: 149, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&q=80', productUrl: 'https://vogacloset.com/qatar/en/women/clothing', category: 'dress', color: ['champagne', 'gold'], fabric: 'polyester', style: ['elegant', 'fitted'], fit: 'fitted', occasion: ['evening'], isOnline: true, inStoreLocation: null, mapsUrl: null },

  // Max Fashion
  { store: 'maxfashion', name: 'Solid Abaya with Belt', price: 119, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1619086303291-0ef7699e4b31?w=400&q=80', productUrl: 'https://www.maxfashion.com/qa/en/department/women', category: 'abaya', color: ['black', 'navy'], fabric: 'polyester', style: ['modest', 'casual'], fit: 'loose', occasion: ['everyday', 'formal'], isOnline: true, inStoreLocation: 'City Center Doha', mapsUrl: 'https://maps.google.com/?q=Max+Fashion+City+Center+Doha' },

  // Splash
  { store: 'splash', name: 'Printed Chiffon Kurta', price: 99, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1622122201714-77da0ca8e5d2?w=400&q=80', productUrl: 'https://www.splashfashions.com/qa/women', category: 'top', color: ['floral', 'red'], fabric: 'chiffon', style: ['modest', 'casual', 'flowy'], fit: 'loose', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: 'City Center Doha', mapsUrl: 'https://maps.google.com/?q=Splash+City+Center+Doha' },

  // LC Waikiki
  { store: 'lcwaikiki', name: 'Long Modest Dress with Pockets', price: 89, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&q=80', productUrl: 'https://www.lcwaikiki.com/en-QA/women/dresses', category: 'dress', color: ['olive', 'khaki'], fabric: 'cotton', style: ['modest', 'casual', 'loose'], fit: 'loose', occasion: ['casual', 'everyday'], isOnline: true, inStoreLocation: 'Mall of Qatar', mapsUrl: 'https://maps.google.com/?q=LC+Waikiki+Mall+of+Qatar' },

  // bfab
  { store: 'bfab', name: 'Premium Linen Co-ord Set', price: 449, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?w=400&q=80', productUrl: 'https://bfab.com/qa_en/women', category: 'top', color: ['beige', 'camel'], fabric: 'linen', style: ['elegant', 'casual'], fit: 'loose', occasion: ['casual', 'work'], isOnline: true, inStoreLocation: null, mapsUrl: null },

  // Galeries Lafayette
  { store: 'galerieslafayette', name: 'Valentino Silk Blouse', price: 2499, currency: 'QAR', imageUrl: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=400&q=80', productUrl: 'https://www.galerieslafayette.qa/women/clothing.html', category: 'blouse', color: ['ivory', 'white'], fabric: 'silk', style: ['elegant', 'formal'], fit: 'fitted', occasion: ['formal', 'evening'], isOnline: true, inStoreLocation: 'Katara Cultural Village', mapsUrl: 'https://maps.google.com/?q=Galeries+Lafayette+Doha' },
];
